# Render deployment configuration for Zoom Webhook Processor
# Updated: 2025-07-02 - Force redeploy to fix topic is not defined error

services:
  - type: web
    name: zoom-webhook-v2
    env: node
    buildCommand: npm install
    startCommand: node webhook-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
